// Generated by CoffeeScript 1.7.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/karakuteco/:parametro', function(request, response) {
    return response.send('Meu ' + request.params.parametro);
  });

  app.listen(3000, function() {
    return console.log('Started server');
  });

}).call(this);


//# sourceMappingURL=index.map
